public class ArthimaticCalculations {
    public void addition(integer x,integer y) {
        integer z=x+y;
        system.debug('Sum of the numbers --> '+z);
    }
    public integer subtraction(integer x,integer y){
        integer z=x-y;
        return z;
        
    
    }
    public void multiplication(integer x,integer y,integer m){
         integer z=x*y*m;
         system.debug('Multiplication of the numbers are--> '+z);
    }
}

        




    


    

