public  class PrimDataTypeDemo4 {
    public void printNewDateTime() {
        Datetime dt3=Datetime.newInstance(2021,5,15,9,5,40);
        system.debug('dt3 is'+dt3);
        Datetime dt4_1=datetime.newInstance(0);
        system.debug(dt4_1);
        Long longTime=123456789789L;
        datetime dt4=datetime.newInstance(longtime);
        system.debug('dt 4 is '+ dt4);
        datetime dt6=datetime.now();
        system.debug(dt6);
        Datetime dt5=datetime.newInstance(1998, 8, 4);
        system.debug(dt5);

    }
}
