public  class SalesforceDeveloper {
    public void myFirstCode() {
        string myFavoriteCity='Canim Istanbul';
        system.debug(myFavoriteCity);
        string myFavoriteMovie='Uzun Hikaye';
        system.debug(myFavoriteMovie);
        string myFavoriteSeason='Sonbahar';
        system.debug(myFavoriteSeason);
    }
        public void myFavorites(){
            integer myFavoriteNumber=3;
            system.debug('Benim sansli sayim' + '  '+ myFavoriteNumber);
            string myCity='St Louis';
            system.debug('Yasadigim sehir  '+ ' ' + myCity+ ' .');


        }
    

    }


